PREFIX     = /usr
MANPREFIX  = $(PREFIX)/share/man
LIBEXECDIR = $(PREFIX)/libexec/editasroot

CC = c99

CPPFLAGS = -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_XOPEN_SOURCE=700 -D'LIBEXECDIR="$(LIBEXECDIR)"'
CFLAGS   =
LDFLAGS  = -s
